version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 10
    assignees:
      - Qrious
