name: Build release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all --strict
        working-directory: ./

      - name: Update plugin version
        run: |
          # Replace the version with the tag in-place, this is NOT committed
          tag=${{ github.ref_name  }}
          sed -i "s/dev-master/$tag/g" ./woocommerce-factuursturen.php

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress --no-suggest
        working-directory: ./

      - name: Create artifact zip
        run: composer run build-archive

      - name: Create release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
          artifacts: woocommerce-factuursturen.zip
          artifactContentType: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
