name: build-prerelease-command
on:
  repository_dispatch:
    types: [build-prerelease-command]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch to test
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          ref: ${{ github.event.client_payload.slash_command.args.named.commit }}

      - name: Composer install packages for syntax check
        run: composer install

      - name: Check for PHP syntax-errors
        run: composer run syntax-check

      - name: Version
        run: echo "::set-output name=version::${{ github.event.client_payload.slash_command.args.named.tag }}"
        id: version

      - name: Update plugin version
        run: |
          # Replace the version with the tag in-place, this is NOT committed
          tag=${{ github.event.client_payload.slash_command.args.named.tag }}
          sed -i "s/dev-master/$tag/g" ./woocommerce-factuursturen.php

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress --no-suggest
        working-directory: ./

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Create artifact zip
        run: composer run build-archive

      - name: Create release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          commit: ${{ github.event.client_payload.pull_request.head.ref }}
          tag: ${{ github.event.client_payload.slash_command.args.named.tag }}
          generateReleaseNotes: true
          artifacts: woocommerce-factuursturen.zip
          artifactContentType: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify build pre-release completed
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.client_payload.slash_command.args.named.pr-id }}
          body: |
            Package ${{ github.event.client_payload.slash_command.args.named.tag }} has been built and is available for testing.
            ${{ steps.create_release.outputs.html_url }}
